### ISSUE TITLE
请问这个有用到websocket吗?

### ISSUE THREAD

**Issue by cathylogs** [tcxiaotudou/weixin#3]
请问这个有用到websocket吗?

**Comment by tcxiaotudou** [comment]
有用到，直接使用的Netty，在线聊天和心跳监测都是基于websocket的。

**Comment by cathylogs** [comment]
谢谢,那能咨询一个问题吗?我微信:972934564,问题:我的毕业设计是:
基于Java及NETTY框架，设计一套完整的WebSocket应用，其中包括服务端、发布端和查询端。在此基础上，实现一个WebSocket的典型应用，如天气发布查询、图书信息发布查询等。


1、服务端至少能支持100个主题查询；
2、服务端至少能支持1000个客户端进行信息订阅；
3、服务端吞吐量不小于10次查询/秒。

我想基于您的项目去改,不知道是不是我想的这样?谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fciasth"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 下午5:02
收件人:&nbsp;"tcxiaotudou/weixin"<weixin@noreply.github.com&gt;;
抄送:&nbsp;"温和与热烈"<972934564@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tcxiaotudou/weixin] 请问这个有用到websocket吗? (#3)





 
有用到，直接使用的Netty，在线聊天和心跳监测都是基于websocket的。
